---
title: My place
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Chaitra's website
description: 
google_analytics: UA-xxxxxxxx-1
mailchimp-list: https://chaitrapaikamath.us2.list-manage.com/subscribe/post?u=b7d484ac855b313b6e4fe384d&amp;id=02268205df
include:
- _pages
permalink: "/:title/"
email: chaitrapaikamath@gmail.com
authors:
  chaitra:
    name: Chaitra
    display_name: Chaitra
    email: chaitrapaikamath@gmail.com
    description: My website with thoughts, opinions and career tips
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-figure
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: 6
paginate_path: "/page:num/"
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
lazyimages: disabled
authorbox: disabled
sass:
  sass_dir: _sass
  style: compressed
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
